### ISSUE TITLE
ProbIoU-aware dynamic label assignment strategy

### ISSUE THREAD

**Issue by zhu011** [Zeba-Xie/RTMDet-R2#1]
想请问一下，这个label assignment现在可以在您的仓库公开吗？

**Comment by Zeba-Xie** [comment]
> 想请问一下，这个label assignment现在可以在您的仓库公开吗？

可以的，本周末整理好后就放上来。

**Comment by zhu011** [comment]
好的谢谢您，期待您的工作！

**Comment by Zeba-Xie** [comment]
> 好的谢谢您，期待您的工作！

已更新，请查收，希望对您的研究有所帮助~

**Comment by zhu011** [comment]
谢谢您的迅速解答，十分感谢
